data:
  text:
    max_length: 50

  audio:
    max_length: 1500

training:
  model_parameters:
    num_heads: 8
    num_blocks: 2
    intermediate_dims: 256

  hyperparameters:
    learning_rate: 0.0001
    batch_size: 8
    epochs: 20

  split:
    train: 0.5
    test: 0.25
    val: 0.25
